---
apiVersion: v1
kind: Pod
metadata:
  name: dnd
  labels:
    component: agent
spec:
  containers:
    - name: dind
      image: shipyardrun/tools:v0.3.0
      command: ["tail", "-f", "/dev/null"]
      securityContext:
        privileged: true
      volumeMounts:
        - name: dind-storage
          mountPath: /var/lib/docker
        - name: dockersock
          mountPath: "/var/run/docker.sock"
  volumes:
    - name: dind-storage
      emptyDir: {}
    - name: dockersock
      hostPath:
        path: /run/k3s/containerd/containerd.sock